rate_limit_rules = []

[[sensitive_prefixes]]
value = "/etc/shadow"
enabled = true

[[sensitive_prefixes]]
value = "/etc/ssl"
enabled = true

[[sensitive_prefixes]]
value = "/root/.ssh"
enabled = true

[[sensitive_prefixes]]
value = "/var/lib/gaia"
enabled = true

[[monitored_services]]
value = "ssh.service"
enabled = true

[[monitored_services]]
value = "nginx.service"
enabled = true

[[exec_whitelist_prefixes]]
value = "/usr/bin"
enabled = true

[[exec_whitelist_prefixes]]
value = "/usr/sbin"
enabled = true

[[exec_whitelist_prefixes]]
value = "/bin"
enabled = true

[[exec_whitelist_prefixes]]
value = "/sbin"
enabled = true

[[blocked_ports]]
port = 4444
enabled = true

[[blocked_ports]]
port = 31337
enabled = true

[baseline_thresholds]
privilege = 20
file_io = 600000
process = 80
network = 160
hotpatch = 50

[[hotpatch.targets]]
binary = "/home/jask/lua"
symbol = "luaB_print"
pid = 626280
enabled = false
patch_action = "replace_function"
override_return_value = 0
replace_lib = "/tmp/gaia-libs/liblua.so.5.5"

[[hotpatch.kernel_livepatch]]
old_func = "cmdline_proc_show"
new_func_body = '''
    seq_puts(m, "GAIA_PROTECTED\n");
    return 0;'''
func_ret = "static int"
func_args = "struct seq_file *m, void *v"
enabled = true
