#!/usr/bin/env bash
# Integration test for gaia kernel livepatch functionality.
#
# Tests the full lifecycle:
#   1. Verify kernel livepatch support
#   2. Build a livepatch module using the same template as gaia
#   3. Load the module and enable the patch
#   4. Verify the patch is active (cmdline_proc_show replaced)
#   5. Disable and unload the module
#   6. Verify the patch is removed
#
# Must be run as root (or with sudo) on a Linux system with:
#   - CONFIG_LIVEPATCH=y
#   - kernel-devel package installed
#   - gcc available
#
# Usage:
#   sudo bash tests/test_kernel_livepatch.sh
#   # or from project root:
#   sudo bash tests/test_kernel_livepatch.sh

set -euo pipefail

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
pass() { echo -e "${GREEN}[PASS]${NC} $*"; }
fail() { echo -e "${RED}[FAIL]${NC} $*"; exit 1; }
info() { echo -e "${YELLOW}[INFO]${NC} $*"; }

# ── Helpers ───────────────────────────────────────────────────────────────────
KERNEL_VER=$(uname -r)
KDIR="/usr/src/kernels/${KERNEL_VER}"
BUILD_DIR=$(mktemp -d /tmp/gaia_klp_test_XXXXXX)
MODULE_NAME="gaia_klp_inttest"
KO_PATH="${BUILD_DIR}/${MODULE_NAME}.ko"

cleanup() {
    info "Cleaning up..."
    # Disable patch if still active
    if [[ -f "/sys/kernel/livepatch/${MODULE_NAME}/enabled" ]]; then
        echo 0 > "/sys/kernel/livepatch/${MODULE_NAME}/enabled" 2>/dev/null || true
        sleep 1
    fi
    # Unload module if loaded
    if lsmod | grep -q "^${MODULE_NAME}"; then
        rmmod "${MODULE_NAME}" 2>/dev/null || true
    fi
    rm -rf "${BUILD_DIR}"
}
trap cleanup EXIT

# ── Preflight checks ──────────────────────────────────────────────────────────
info "=== Gaia Kernel Livepatch Integration Test ==="
info "Kernel: ${KERNEL_VER}"
info "Build dir: ${BUILD_DIR}"

# Must be root
if [[ $EUID -ne 0 ]]; then
    fail "This test must be run as root"
fi

# Check kernel livepatch support
if ! zcat /proc/config.gz 2>/dev/null | grep -q "CONFIG_LIVEPATCH=y" && \
   ! grep -q "CONFIG_LIVEPATCH=y" "/boot/config-${KERNEL_VER}" 2>/dev/null && \
   ! grep -q "CONFIG_LIVEPATCH=y" "${KDIR}/.config" 2>/dev/null; then
    # Fall back to checking sysfs
    if [[ ! -d "/sys/kernel/livepatch" ]]; then
        fail "Kernel does not support livepatch (CONFIG_LIVEPATCH not found)"
    fi
fi
pass "Kernel livepatch support confirmed"

# Check kernel-devel
if [[ ! -d "${KDIR}" ]]; then
    fail "Kernel build directory not found: ${KDIR}\nInstall: dnf install kernel-devel-${KERNEL_VER}"
fi
if [[ ! -f "${KDIR}/include/linux/livepatch.h" ]]; then
    fail "livepatch.h not found in ${KDIR}/include/linux/\nInstall: dnf install kernel-devel-${KERNEL_VER}"
fi
pass "Kernel-devel headers found at ${KDIR}"

# Check gcc
if ! command -v gcc &>/dev/null; then
    fail "gcc not found; install gcc"
fi
pass "gcc available: $(gcc --version | head -1)"

# ── Step 1: Generate C source (same template as gaia livepatch.rs) ────────────
info "--- Step 1: Generate C module source ---"

cat > "${BUILD_DIR}/${MODULE_NAME}.c" << 'EOF'
// Auto-generated by gaia integration test
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/livepatch.h>
#include <linux/seq_file.h>

MODULE_LICENSE("GPL");
MODULE_AUTHOR("gaia-xdp");
MODULE_DESCRIPTION("gaia kernel livepatch integration test");
MODULE_INFO(livepatch, "Y");

static int gaia_klp_inttest_new_func_0(struct seq_file *m, void *v)
{
    seq_puts(m, "GAIA_LIVEPATCH_TEST_ACTIVE\n");
    return 0;
}

static struct klp_func gaia_klp_inttest_funcs_0[] = {
    { .old_name = "cmdline_proc_show", .new_func = gaia_klp_inttest_new_func_0 },
    { }
};

static struct klp_object gaia_klp_inttest_objs[] = {
    { .name = NULL, .funcs = gaia_klp_inttest_funcs_0 },
    { }
};

static struct klp_patch gaia_klp_inttest_patch = {
    .mod  = THIS_MODULE,
    .objs = gaia_klp_inttest_objs,
};

static int __init gaia_klp_inttest_init(void)
{
    return klp_register_patch(&gaia_klp_inttest_patch);
}

static void __exit gaia_klp_inttest_exit(void)
{
    klp_unregister_patch(&gaia_klp_inttest_patch);
}

module_init(gaia_klp_inttest_init);
module_exit(gaia_klp_inttest_exit);
EOF

pass "C source generated: ${BUILD_DIR}/${MODULE_NAME}.c"

# ── Step 2: Generate Makefile ─────────────────────────────────────────────────
info "--- Step 2: Generate Makefile ---"

cat > "${BUILD_DIR}/Makefile" << EOF
obj-m += ${MODULE_NAME}.o
KDIR := ${KDIR}
PWD  := \$(shell pwd)

all:
	\$(MAKE) -C \$(KDIR) M=\$(PWD) modules

clean:
	\$(MAKE) -C \$(KDIR) M=\$(PWD) clean
EOF

pass "Makefile generated"

# ── Step 3: Build the module ──────────────────────────────────────────────────
info "--- Step 3: Build kernel module ---"

make -C "${BUILD_DIR}" 2>&1 | grep -E "^(  CC|  LD|  MODPOST|make\[|Error|error)" || true

if [[ ! -f "${KO_PATH}" ]]; then
    fail "Build failed: ${KO_PATH} not found"
fi
pass "Module built: ${KO_PATH}"

# Verify MODULE_INFO(livepatch, "Y") is present
if ! modinfo "${KO_PATH}" | grep -q "^livepatch:.*Y"; then
    fail "Module is missing livepatch modinfo tag"
fi
pass "Module has livepatch modinfo tag"

# ── Step 4: Load module ───────────────────────────────────────────────────────
info "--- Step 4: Load module ---"

ORIGINAL_CMDLINE=$(cat /proc/cmdline)
info "Original /proc/cmdline: ${ORIGINAL_CMDLINE}"

insmod "${KO_PATH}"
if ! lsmod | grep -q "^${MODULE_NAME}"; then
    fail "insmod succeeded but module not in lsmod"
fi
pass "Module loaded: ${MODULE_NAME}"

# ── Step 5: Enable the patch ──────────────────────────────────────────────────
info "--- Step 5: Enable livepatch ---"

SYSFS="/sys/kernel/livepatch/${MODULE_NAME}/enabled"
if [[ ! -f "${SYSFS}" ]]; then
    fail "sysfs entry not found: ${SYSFS}"
fi

echo 1 > "${SYSFS}"

# Wait for enabled to become 1
for i in $(seq 1 30); do
    ENABLED=$(cat "${SYSFS}" 2>/dev/null || echo "0")
    if [[ "${ENABLED}" == "1" ]]; then
        break
    fi
    sleep 0.2
done

ENABLED=$(cat "${SYSFS}")
if [[ "${ENABLED}" != "1" ]]; then
    fail "Livepatch did not become enabled (got: ${ENABLED})"
fi
pass "Livepatch enabled (sysfs enabled=1)"

# ── Step 6: Verify patch is active ───────────────────────────────────────────
info "--- Step 6: Verify patch effect ---"

PATCHED_CMDLINE=$(cat /proc/cmdline)
info "Patched /proc/cmdline: ${PATCHED_CMDLINE}"

if [[ "${PATCHED_CMDLINE}" != "GAIA_LIVEPATCH_TEST_ACTIVE" ]]; then
    fail "/proc/cmdline not patched (expected 'GAIA_LIVEPATCH_TEST_ACTIVE', got '${PATCHED_CMDLINE}')"
fi
pass "/proc/cmdline shows patched value"

# ── Step 7: Disable the patch ─────────────────────────────────────────────────
info "--- Step 7: Disable livepatch ---"

echo 0 > "${SYSFS}"

# Wait for enabled to become 0
for i in $(seq 1 30); do
    ENABLED=$(cat "${SYSFS}" 2>/dev/null || echo "0")
    if [[ "${ENABLED}" == "0" ]]; then
        break
    fi
    sleep 0.2
done

ENABLED=$(cat "${SYSFS}")
if [[ "${ENABLED}" != "0" ]]; then
    fail "Livepatch did not become disabled (got: ${ENABLED})"
fi
pass "Livepatch disabled (sysfs enabled=0)"

# ── Step 8: Unload module ─────────────────────────────────────────────────────
info "--- Step 8: Unload module ---"

rmmod "${MODULE_NAME}"
if lsmod | grep -q "^${MODULE_NAME}"; then
    fail "rmmod succeeded but module still in lsmod"
fi
pass "Module unloaded"

# ── Step 9: Verify patch removed ──────────────────────────────────────────────
info "--- Step 9: Verify patch removed ---"

RESTORED_CMDLINE=$(cat /proc/cmdline)
info "Restored /proc/cmdline: ${RESTORED_CMDLINE}"

if [[ "${RESTORED_CMDLINE}" == "GAIA_LIVEPATCH_TEST_ACTIVE" ]]; then
    fail "/proc/cmdline still shows patched value after unload"
fi
if [[ "${RESTORED_CMDLINE}" != "${ORIGINAL_CMDLINE}" ]]; then
    fail "/proc/cmdline restored to unexpected value: '${RESTORED_CMDLINE}' (expected '${ORIGINAL_CMDLINE}')"
fi
pass "/proc/cmdline restored to original"

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}=== All integration tests passed ===${NC}"
echo ""
echo "Kernel livepatch lifecycle verified:"
echo "  ✓ Kernel support check"
echo "  ✓ Module source generation (same template as gaia livepatch.rs)"
echo "  ✓ Module compilation"
echo "  ✓ Module load (insmod)"
echo "  ✓ Patch enable (sysfs)"
echo "  ✓ Patch effect verified (/proc/cmdline)"
echo "  ✓ Patch disable (sysfs)"
echo "  ✓ Module unload (rmmod)"
echo "  ✓ Patch removal verified (/proc/cmdline restored)"
