#![no_std]

// This file exists to enable the library target for the gaia-xdp-ebpf crate.
//
// The eBPF programs (tracepoints, kprobe/kretprobe, uprobe/uretprobe) are all
// defined in src/main.rs which is compiled as the binary target.
//
// Kernel type bindings generated by rust-bindgen are provided as separate modules
// (src/vmlinux.rs, src/file.rs, src/lsm.rs, src/mm.rs, src/net.rs, src/syscall.rs)
// and can be re-exported here for downstream eBPF programs that depend on this crate
// as a library.
