/* automatically generated by rust-bindgen 0.72.1 */

pub type __s32 = ::aya_ebpf::cty::c_int;
pub type s32 = __s32;
pub type __u32 = ::aya_ebpf::cty::c_uint;
pub type u32_ = __u32;
pub type __u64 = ::aya_ebpf::cty::c_ulonglong;
pub type u64_ = __u64;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct user_pt_regs {
    pub regs: [__u64; 31usize],
    pub sp: __u64,
    pub pc: __u64,
    pub pstate: __u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct frame_record {
    pub fp: u64_,
    pub lr: u64_,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct frame_record_meta {
    pub record: frame_record,
    pub type_: u64_,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct pt_regs {
    pub __bindgen_anon_1: pt_regs__bindgen_ty_1,
    pub orig_x0: u64_,
    pub syscallno: s32,
    pub pmr: u32_,
    pub sdei_ttbr1: u64_,
    pub stackframe: frame_record_meta,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union pt_regs__bindgen_ty_1 {
    pub user_regs: user_pt_regs,
    pub __bindgen_anon_1: pt_regs__bindgen_ty_1__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pt_regs__bindgen_ty_1__bindgen_ty_1 {
    pub regs: [u64_; 31usize],
    pub sp: u64_,
    pub pc: u64_,
    pub pstate: u64_,
}
