/// Kernel live patching support via the Linux livepatch API.
///
/// This module generates a C kernel module from a template, compiles it with the
/// running kernel's build system, loads it via `insmod`, and enables/disables it
/// through the `/sys/kernel/livepatch/<name>/enabled` sysfs interface.
///
/// Requires:
/// - `CONFIG_LIVEPATCH=y` in the running kernel
/// - `kernel-devel` package installed (provides `/usr/src/kernels/<ver>/`)
/// - Root privileges (CAP_SYS_MODULE)
use std::{
    collections::HashMap,
    fs,
    path::{Path, PathBuf},
    time::Duration,
};

use anyhow::{Context, Result, anyhow, bail};
use log::{info, warn};
use serde::{Deserialize, Serialize};
use tokio::process::Command;

// ── Public types ──────────────────────────────────────────────────────────────

/// A single kernel livepatch target: replaces one kernel function.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct KernelLivepatchTarget {
    /// Name of the kernel function to replace (must be non-inlined and exported in kallsyms).
    pub old_func: String,
    /// The C source of the replacement function body (everything inside `{ ... }`).
    /// The replacement must have the same signature as the original.
    pub new_func_body: String,
    /// C type signature of the replacement function, e.g.
    /// `"static int"`.  Defaults to `"static int"`.
    #[serde(default = "default_func_ret")]
    pub func_ret: String,
    /// Argument list string, e.g. `"struct seq_file *m, void *v"`.
    /// Defaults to `"void"`.
    #[serde(default = "default_func_args")]
    pub func_args: String,
    /// Optional: kernel module name that owns the function (NULL / empty = vmlinux).
    #[serde(default)]
    pub obj_name: Option<String>,
    /// Whether this target is enabled.
    #[serde(default = "default_true")]
    pub enabled: bool,
}

fn default_func_ret() -> String {
    "static int".to_string()
}

fn default_func_args() -> String {
    "void".to_string()
}

fn default_true() -> bool {
    true
}

/// State of a loaded livepatch module.
#[derive(Debug, Clone, PartialEq)]
pub enum LivepatchState {
    /// Module is built and loaded, patch is active.
    Active,
    /// Module is loaded but patch is disabled (transitioning out).
    Disabling,
    /// Module is not loaded.
    Unloaded,
}

/// A managed livepatch module instance.
pub struct LivepatchModule {
    /// Unique module name (e.g. `gaia_klp_0`).
    pub name: String,
    /// Directory where the module source and .ko are stored.
    pub build_dir: PathBuf,
    /// Current state.
    pub state: LivepatchState,
}

// ── Module generation & build ─────────────────────────────────────────────────

/// Generate a C kernel module source for the given targets.
///
/// All targets are bundled into a single module with one `klp_patch`.
/// Each target becomes one `klp_func` entry.
pub fn generate_module_source(
    module_name: &str,
    targets: &[KernelLivepatchTarget],
) -> Result<String> {
    if targets.is_empty() {
        bail!("no livepatch targets provided");
    }

    let mut src = String::new();

    // Header — include a broad set of common kernel headers so that
    // user-supplied function bodies can use seq_file, net, fs, sched, etc.
    // without needing to specify includes themselves.
    src.push_str(&format!(
        r#"// Auto-generated by gaia — do not edit manually.
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/livepatch.h>
#include <linux/seq_file.h>
#include <linux/fs.h>
#include <linux/sched.h>
#include <linux/uaccess.h>
#include <linux/slab.h>
#include <linux/net.h>
#include <linux/in.h>
#include <linux/string.h>

MODULE_LICENSE("GPL");
MODULE_AUTHOR("gaia-xdp");
MODULE_DESCRIPTION("gaia kernel livepatch: {module_name}");
MODULE_INFO(livepatch, "Y");

"#
    ));

    // Replacement function definitions
    for (i, t) in targets.iter().enumerate() {
        let replacement_name = replacement_func_name(module_name, i);
        src.push_str(&format!(
            "{ret} {name}({args})\n{{\n{body}\n}}\n\n",
            ret = t.func_ret,
            name = replacement_name,
            args = t.func_args,
            body = t.new_func_body,
        ));
    }

    // klp_func arrays — one per object (grouped by obj_name)
    // Build a map: obj_name -> list of (index, target)
    let mut obj_groups: Vec<(Option<String>, Vec<(usize, &KernelLivepatchTarget)>)> = Vec::new();
    for (i, t) in targets.iter().enumerate() {
        let key = t.obj_name.clone();
        if let Some(g) = obj_groups.iter_mut().find(|(k, _)| k == &key) {
            g.1.push((i, t));
        } else {
            obj_groups.push((key, vec![(i, t)]));
        }
    }

    for (obj_idx, (obj_name, funcs)) in obj_groups.iter().enumerate() {
        let arr_name = format!("{module_name}_funcs_{obj_idx}");
        src.push_str(&format!("static struct klp_func {arr_name}[] = {{\n"));
        for (i, t) in funcs {
            let replacement_name = replacement_func_name(module_name, *i);
            src.push_str(&format!(
                "    {{ .old_name = \"{old}\", .new_func = {new} }},\n",
                old = t.old_func,
                new = replacement_name,
            ));
        }
        src.push_str("    { }\n};\n\n");

        let obj_name_c = match obj_name {
            Some(n) => format!("\"{n}\""),
            None => "NULL".to_string(),
        };
        let _ = obj_name_c; // used below
    }

    // klp_object array
    src.push_str(&format!(
        "static struct klp_object {module_name}_objs[] = {{\n"
    ));
    for (obj_idx, (obj_name, _)) in obj_groups.iter().enumerate() {
        let arr_name = format!("{module_name}_funcs_{obj_idx}");
        let name_c = match obj_name {
            Some(n) => format!("\"{n}\""),
            None => "NULL".to_string(),
        };
        src.push_str(&format!(
            "    {{ .name = {name_c}, .funcs = {arr_name} }},\n"
        ));
    }
    src.push_str("    { }\n};\n\n");

    // klp_patch
    src.push_str(&format!(
        r#"static struct klp_patch {module_name}_patch = {{
    .mod  = THIS_MODULE,
    .objs = {module_name}_objs,
}};

static int __init {module_name}_init(void)
{{
    return klp_register_patch(&{module_name}_patch);
}}

static void __exit {module_name}_exit(void)
{{
    klp_unregister_patch(&{module_name}_patch);
}}

module_init({module_name}_init);
module_exit({module_name}_exit);
"#
    ));

    Ok(src)
}

/// Generate the Makefile for the livepatch module.
pub fn generate_makefile(module_name: &str, kernel_dir: &str) -> String {
    format!(
        r#"obj-m += {module_name}.o
KDIR := {kernel_dir}
PWD  := $(shell pwd)

all:
	$(MAKE) -C $(KDIR) M=$(PWD) modules

clean:
	$(MAKE) -C $(KDIR) M=$(PWD) clean
"#
    )
}

fn replacement_func_name(module_name: &str, idx: usize) -> String {
    format!("{module_name}_new_func_{idx}")
}

// ── Kernel detection ──────────────────────────────────────────────────────────

/// Detect the kernel build directory for the running kernel.
pub async fn detect_kernel_build_dir() -> Result<String> {
    let uname = Command::new("uname")
        .arg("-r")
        .output()
        .await
        .context("run uname -r")?;
    let version = String::from_utf8(uname.stdout)
        .context("uname output")?
        .trim()
        .to_string();

    // Try /usr/src/kernels/<version> (RPM-based distros like OpenEuler/RHEL)
    let rpm_path = format!("/usr/src/kernels/{version}");
    if Path::new(&rpm_path).exists() {
        return Ok(rpm_path);
    }

    // Try /lib/modules/<version>/build symlink (Debian/Ubuntu)
    let deb_path = format!("/lib/modules/{version}/build");
    if Path::new(&deb_path).exists() {
        return Ok(deb_path);
    }

    bail!(
        "kernel build directory not found for {version}; \
         install kernel-devel or linux-headers-{version}"
    )
}

/// Check if the running kernel has livepatch support.
pub async fn check_livepatch_support() -> Result<()> {
    let config_paths = {
        let uname = Command::new("uname")
            .arg("-r")
            .output()
            .await
            .context("run uname -r")?;
        let ver = String::from_utf8(uname.stdout)?.trim().to_string();
        vec![
            format!("/proc/config.gz"),
            format!("/boot/config-{ver}"),
            format!("/usr/src/kernels/{ver}/.config"),
        ]
    };

    for path in &config_paths {
        if let Ok(content) = read_maybe_gzipped(path).await {
            if content.contains("CONFIG_LIVEPATCH=y") {
                return Ok(());
            }
            // If we found the config but no livepatch, it's definitely not supported.
            bail!("kernel config found at {path} but CONFIG_LIVEPATCH is not enabled");
        }
    }

    // If we can't find the config, check for the sysfs directory as a proxy.
    if Path::new("/sys/kernel/livepatch").exists() {
        return Ok(());
    }

    bail!(
        "cannot determine livepatch support; \
         install kernel-devel or ensure /sys/kernel/livepatch exists"
    )
}

async fn read_maybe_gzipped(path: &str) -> Result<String> {
    if path.ends_with(".gz") {
        let out = Command::new("zcat")
            .arg(path)
            .output()
            .await
            .context("zcat config")?;
        if !out.status.success() {
            bail!("zcat failed");
        }
        Ok(String::from_utf8_lossy(&out.stdout).into_owned())
    } else {
        fs::read_to_string(path).context("read config")
    }
}

// ── Build & load ──────────────────────────────────────────────────────────────

/// Build a livepatch kernel module from the given targets.
///
/// Returns a `LivepatchModule` with `state = Unloaded` (not yet inserted).
pub async fn build_livepatch_module(
    module_name: &str,
    targets: &[KernelLivepatchTarget],
    build_base: &Path,
) -> Result<LivepatchModule> {
    let kernel_dir = detect_kernel_build_dir()
        .await
        .context("detect kernel build dir")?;

    let build_dir = build_base.join(module_name);
    fs::create_dir_all(&build_dir)
        .with_context(|| format!("create build dir {}", build_dir.display()))?;

    // Write C source
    let src = generate_module_source(module_name, targets)?;
    let c_path = build_dir.join(format!("{module_name}.c"));
    fs::write(&c_path, &src).with_context(|| format!("write {}", c_path.display()))?;
    info!("livepatch: wrote C source to {}", c_path.display());

    // Write Makefile
    let makefile = generate_makefile(module_name, &kernel_dir);
    let mk_path = build_dir.join("Makefile");
    fs::write(&mk_path, &makefile).with_context(|| format!("write {}", mk_path.display()))?;

    // Build
    info!(
        "livepatch: building module {} in {}",
        module_name,
        build_dir.display()
    );
    let output = Command::new("make")
        .current_dir(&build_dir)
        .output()
        .await
        .context("run make")?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        let stdout = String::from_utf8_lossy(&output.stdout);
        bail!("livepatch module build failed:\nstdout:\n{stdout}\nstderr:\n{stderr}");
    }

    let ko_path = build_dir.join(format!("{module_name}.ko"));
    if !ko_path.exists() {
        bail!("build succeeded but {} not found", ko_path.display());
    }

    info!("livepatch: module built: {}", ko_path.display());
    Ok(LivepatchModule {
        name: module_name.to_string(),
        build_dir,
        state: LivepatchState::Unloaded,
    })
}

/// Load (insmod) a built livepatch module and enable the patch.
///
/// The caller must have CAP_SYS_MODULE (i.e. run as root).
pub async fn load_livepatch_module(module: &mut LivepatchModule) -> Result<()> {
    let ko_path = module.build_dir.join(format!("{}.ko", module.name));

    // If the module is already in the kernel (e.g. from a previous daemon run),
    // unload it first so insmod doesn't fail with "File exists".
    if is_module_loaded(&module.name).await {
        warn!(
            "livepatch: module {} already in kernel, unloading first",
            module.name
        );
        force_rmmod(&module.name).await?;
    }

    info!("livepatch: loading {}", ko_path.display());
    let out = Command::new("insmod")
        .arg(&ko_path)
        .output()
        .await
        .context("insmod")?;

    if !out.status.success() {
        let stderr = String::from_utf8_lossy(&out.stderr);
        bail!("insmod failed: {stderr}");
    }

    // Enable the patch via sysfs
    enable_livepatch(&module.name).await?;
    module.state = LivepatchState::Active;
    info!("livepatch: module {} active", module.name);
    Ok(())
}

/// Return true if a kernel module with the given name is currently loaded.
async fn is_module_loaded(name: &str) -> bool {
    // Module names in /proc/modules use underscores; hyphens become underscores too.
    let normalized = name.replace('-', "_");
    let out = Command::new("lsmod")
        .output()
        .await
        .unwrap_or_else(|_| std::process::Output {
            status: std::process::ExitStatus::default(),
            stdout: vec![],
            stderr: vec![],
        });
    String::from_utf8_lossy(&out.stdout)
        .lines()
        .any(|line| line.split_whitespace().next() == Some(normalized.as_str()))
}

/// Disable (via sysfs) and rmmod a module that may not be tracked by the manager.
async fn force_rmmod(name: &str) -> Result<()> {
    let sysfs = format!("/sys/kernel/livepatch/{name}/enabled");
    if Path::new(&sysfs).exists() {
        let _ = fs::write(&sysfs, "0\n");
        wait_for_transition(name, false, Duration::from_secs(15)).await?;
        wait_for_use_count_zero(name, Duration::from_secs(15)).await?;
    }
    let out = Command::new("rmmod")
        .arg(name)
        .output()
        .await
        .context("rmmod")?;
    if !out.status.success() {
        let stderr = String::from_utf8_lossy(&out.stderr);
        bail!("rmmod {name} failed: {stderr}");
    }
    Ok(())
}

/// Disable and unload (rmmod) a livepatch module.
pub async fn unload_livepatch_module(module: &mut LivepatchModule) -> Result<()> {
    if module.state == LivepatchState::Unloaded {
        return Ok(());
    }

    // Disable first (write 0 to sysfs)
    let sysfs = format!("/sys/kernel/livepatch/{}/enabled", module.name);
    if Path::new(&sysfs).exists() {
        info!("livepatch: disabling {}", module.name);
        fs::write(&sysfs, "0\n").with_context(|| format!("disable via {sysfs}"))?;
        module.state = LivepatchState::Disabling;

        // Wait for the sysfs enabled flag to reach 0 (transition started).
        wait_for_transition(&module.name, false, Duration::from_secs(30)).await?;

        // After enabled=0, the kernel still needs to finish the consistency
        // model — all tasks must pass through a safe point before the module
        // use count drops to 0.  Poll /proc/modules until use count is 0.
        wait_for_use_count_zero(&module.name, Duration::from_secs(30)).await?;
    }

    // rmmod
    info!("livepatch: unloading module {}", module.name);
    let out = Command::new("rmmod")
        .arg(&module.name)
        .output()
        .await
        .context("rmmod")?;

    if !out.status.success() {
        let stderr = String::from_utf8_lossy(&out.stderr);
        bail!("rmmod failed: {stderr}");
    }

    module.state = LivepatchState::Unloaded;
    info!("livepatch: module {} unloaded", module.name);
    Ok(())
}

/// Enable a loaded (but not yet active) livepatch by writing 1 to sysfs.
async fn enable_livepatch(name: &str) -> Result<()> {
    let sysfs = format!("/sys/kernel/livepatch/{name}/enabled");
    // The sysfs entry may take a moment to appear after insmod
    for _ in 0..20 {
        if Path::new(&sysfs).exists() {
            break;
        }
        tokio::time::sleep(Duration::from_millis(100)).await;
    }
    if !Path::new(&sysfs).exists() {
        bail!("sysfs entry {sysfs} not found after insmod");
    }

    fs::write(&sysfs, "1\n").with_context(|| format!("enable via {sysfs}"))?;

    // Wait for enabled to become 1
    wait_for_transition(name, true, Duration::from_secs(30)).await?;
    Ok(())
}

/// Poll `enabled` until it reaches `target_value` or timeout.
async fn wait_for_transition(name: &str, target: bool, timeout: Duration) -> Result<()> {
    let sysfs = format!("/sys/kernel/livepatch/{name}/enabled");
    let target_str = if target { "1" } else { "0" };
    let deadline = tokio::time::Instant::now() + timeout;

    loop {
        if tokio::time::Instant::now() >= deadline {
            bail!("timeout waiting for livepatch {name} to reach enabled={target_str}");
        }
        let val = fs::read_to_string(&sysfs).unwrap_or_default();
        if val.trim() == target_str {
            return Ok(());
        }
        tokio::time::sleep(Duration::from_millis(200)).await;
    }
}

/// Poll `/proc/modules` until the module's use count reaches 0 or timeout.
///
/// After a livepatch is disabled (enabled=0), the kernel consistency model
/// requires all tasks to pass through a safe point before the module can be
/// unloaded.  The use count in `/proc/modules` drops to 0 once that is done.
async fn wait_for_use_count_zero(name: &str, timeout: Duration) -> Result<()> {
    let normalized = name.replace('-', "_");
    let deadline = tokio::time::Instant::now() + timeout;

    loop {
        if tokio::time::Instant::now() >= deadline {
            bail!("timeout waiting for module {name} use count to reach 0");
        }
        let content = fs::read_to_string("/proc/modules").unwrap_or_default();
        // /proc/modules format: name size usecount deps state offset
        let use_count = content
            .lines()
            .find(|line| line.split_whitespace().next() == Some(normalized.as_str()))
            .and_then(|line| line.split_whitespace().nth(2))
            .and_then(|s| s.parse::<i64>().ok());

        match use_count {
            Some(0) => return Ok(()),
            None => return Ok(()), // module no longer in /proc/modules
            _ => {}
        }
        tokio::time::sleep(Duration::from_millis(200)).await;
    }
}

// ── Status query ──────────────────────────────────────────────────────────────

/// Query the current enabled state from sysfs.
pub fn query_livepatch_enabled(name: &str) -> Option<bool> {
    let sysfs = format!("/sys/kernel/livepatch/{name}/enabled");
    fs::read_to_string(&sysfs)
        .ok()
        .and_then(|s| s.trim().parse::<u8>().ok())
        .map(|v| v != 0)
}

/// List all active livepatch modules from sysfs.
#[allow(dead_code)]
pub fn list_active_livepatches() -> Vec<String> {
    fs::read_dir("/sys/kernel/livepatch")
        .map(|rd| {
            rd.filter_map(|e| e.ok())
                .map(|e| e.file_name().to_string_lossy().into_owned())
                .collect()
        })
        .unwrap_or_default()
}

// ── Manager ───────────────────────────────────────────────────────────────────

/// Manages a collection of livepatch modules.
pub struct LivepatchManager {
    modules: HashMap<String, LivepatchModule>,
    build_base: PathBuf,
    next_id: u32,
}

impl LivepatchManager {
    /// Create a new manager. `build_base` is where module source/binaries are stored.
    pub fn new(build_base: impl Into<PathBuf>) -> Self {
        Self {
            modules: HashMap::new(),
            build_base: build_base.into(),
            next_id: 0,
        }
    }

    /// Build, load, and activate a new livepatch from `targets`.
    /// Returns the module name assigned.
    pub async fn apply(&mut self, targets: &[KernelLivepatchTarget]) -> Result<String> {
        let name = format!("gaia_klp_{}", self.next_id);
        self.next_id += 1;

        let mut module = build_livepatch_module(&name, targets, &self.build_base)
            .await
            .with_context(|| format!("build livepatch {name}"))?;

        load_livepatch_module(&mut module)
            .await
            .with_context(|| format!("load livepatch {name}"))?;

        self.modules.insert(name.clone(), module);
        Ok(name)
    }

    /// Disable and unload a livepatch by name.
    pub async fn remove(&mut self, name: &str) -> Result<()> {
        let module = self
            .modules
            .get_mut(name)
            .ok_or_else(|| anyhow!("livepatch module {name} not found"))?;
        unload_livepatch_module(module).await?;
        self.modules.remove(name);
        Ok(())
    }

    /// Remove all active livepatches and reset the id counter.
    /// Also cleans up any stale gaia_klp_* modules not tracked by this manager.
    pub async fn remove_all(&mut self) {
        let names: Vec<String> = self.modules.keys().cloned().collect();
        for name in names {
            if let Err(e) = self.remove(&name).await {
                warn!("livepatch: failed to remove {name}: {e:#}");
            }
        }
        // Clean up any modules that were loaded outside this manager instance
        // (e.g. from a previous reload that failed mid-way).
        self.cleanup_stale_modules().await;
        self.next_id = 0;
    }

    /// Unload any gaia_klp_* modules left in the kernel from a previous daemon
    /// run.  Called once at startup so the manager starts from a clean state.
    pub async fn cleanup_stale_modules(&mut self) {
        let out = match Command::new("lsmod").output().await {
            Ok(o) => o,
            Err(_) => return,
        };
        let stale: Vec<String> = String::from_utf8_lossy(&out.stdout)
            .lines()
            .filter_map(|line| {
                let name = line.split_whitespace().next()?;
                if name.starts_with("gaia_klp_") {
                    Some(name.to_string())
                } else {
                    None
                }
            })
            .collect();

        for name in stale {
            info!("livepatch: removing stale module {name} from previous run");
            if let Err(e) = force_rmmod(&name).await {
                warn!("livepatch: could not remove stale module {name}: {e:#}");
            }
        }
    }

    /// Return status of all managed modules.
    pub fn status(&self) -> Vec<LivepatchStatus> {
        self.modules
            .values()
            .map(|m| LivepatchStatus {
                name: m.name.clone(),
                state: format!("{:?}", m.state),
                enabled: query_livepatch_enabled(&m.name),
                build_dir: m.build_dir.to_string_lossy().into_owned(),
            })
            .collect()
    }
}

/// Serializable status of a livepatch module.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LivepatchStatus {
    pub name: String,
    pub state: String,
    pub enabled: Option<bool>,
    pub build_dir: String,
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_target() -> KernelLivepatchTarget {
        KernelLivepatchTarget {
            old_func: "cmdline_proc_show".to_string(),
            new_func_body: r#"    seq_puts(m, "GAIA_PATCHED\n");
    return 0;"#
                .to_string(),
            func_ret: "static int".to_string(),
            func_args: "struct seq_file *m, void *v".to_string(),
            obj_name: None,
            enabled: true,
        }
    }

    #[test]
    fn generates_valid_c_source() {
        let target = sample_target();
        let src = generate_module_source("gaia_klp_0", &[target]).unwrap();

        assert!(src.contains("MODULE_INFO(livepatch, \"Y\")"));
        assert!(src.contains("MODULE_LICENSE(\"GPL\")"));
        assert!(src.contains("#include <linux/seq_file.h>"));
        assert!(src.contains("#include <linux/fs.h>"));
        assert!(src.contains("klp_register_patch"));
        assert!(src.contains("klp_unregister_patch"));
        assert!(src.contains("gaia_klp_0_new_func_0"));
        assert!(src.contains(".old_name = \"cmdline_proc_show\""));
        assert!(src.contains(".name = NULL"));
        assert!(src.contains("GAIA_PATCHED"));
    }

    #[test]
    fn generates_module_source_with_obj_name() {
        let mut target = sample_target();
        target.obj_name = Some("ext4".to_string());
        let src = generate_module_source("gaia_klp_ext4", &[target]).unwrap();

        assert!(src.contains(".name = \"ext4\""));
    }

    #[test]
    fn generates_multiple_targets() {
        let t1 = sample_target();
        let t2 = KernelLivepatchTarget {
            old_func: "another_func".to_string(),
            new_func_body: "return 42;".to_string(),
            func_ret: "static long".to_string(),
            func_args: "int x".to_string(),
            obj_name: None,
            enabled: true,
        };
        let src = generate_module_source("gaia_klp_multi", &[t1, t2]).unwrap();

        assert!(src.contains("gaia_klp_multi_new_func_0"));
        assert!(src.contains("gaia_klp_multi_new_func_1"));
        assert!(src.contains(".old_name = \"cmdline_proc_show\""));
        assert!(src.contains(".old_name = \"another_func\""));
    }

    #[test]
    fn fails_on_empty_targets() {
        let result = generate_module_source("gaia_klp_empty", &[]);
        assert!(result.is_err());
    }

    #[test]
    fn generates_makefile() {
        let mk = generate_makefile("gaia_klp_0", "/usr/src/kernels/6.6.0");
        assert!(mk.contains("obj-m += gaia_klp_0.o"));
        assert!(mk.contains("KDIR := /usr/src/kernels/6.6.0"));
        assert!(mk.contains("$(MAKE) -C $(KDIR)"));
    }

    #[test]
    fn replacement_func_name_format() {
        assert_eq!(
            replacement_func_name("gaia_klp_0", 0),
            "gaia_klp_0_new_func_0"
        );
        assert_eq!(
            replacement_func_name("gaia_klp_0", 3),
            "gaia_klp_0_new_func_3"
        );
    }

    #[test]
    fn generated_source_has_correct_structure() {
        let target = sample_target();
        let src = generate_module_source("test_mod", &[target]).unwrap();

        // Verify module init/exit are present
        assert!(src.contains("module_init(test_mod_init)"));
        assert!(src.contains("module_exit(test_mod_exit)"));

        // Verify klp_patch struct
        assert!(src.contains("static struct klp_patch test_mod_patch"));
        assert!(src.contains(".mod  = THIS_MODULE"));
        assert!(src.contains(".objs = test_mod_objs"));

        // Verify null-terminated arrays
        assert!(src.contains("{ }\n};"));
    }
}
